version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis
    container_name: redis
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  
    volumes:
      - ./redis_volume:/data
  
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    restart: on-failure
    environment:
      - SA_PASSWORD=Brt_z!py
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.debug
    container_name: workshop_api
    ports:
      - "5000:80"
    volumes: 
      - ./api/bin/Debug/netcoreapp2.2/:/app
    depends_on:
      - mssql
      - redis
      - rabbitmq

  ui:
    build: 
      context: ./react_ui
      dockerfile: Dockerfile
    container_name: workshop_ui
    restart: on-failure
    ports:
      - '5001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api